### ISSUE TITLE
blanks are removed in where clauses

### ISSUE THREAD

**Issue by webian** [franzholz/table#2] opened 2020-05-23 12:38 UTC
https://github.com/franzholz/tt_products/blob/d4a0acffba8e402a5d072a6c9facd37563db2813/view/class.tx_ttproducts_list_view.php#L1020 calls https://github.com/franzholz/table/blob/325b56ef7c0f47530afdfd20877f5d9853e9cbc4/lib/class.tx_table_db.php#L812 with input ` AND (inStock > 0) `
This method outputs `AND(product.inStock > 0)` that's wrong SQL because of missing space between `AND` and `(product`

**Comment by webian** [comment] 2020-05-23 13:04
Never mind. Even if there's no space, it causes no problem in query execution.

**Comment by franzholz** [comment] 2020-05-23 13:49
This is still a bug which should be fixed, even if no SQL error is caused by it.

**Closed as completed** 2020-05-23 14:06 UTC
Labels: bug

**Comment by webian** [comment] 2020-05-24 07:59
https://github.com/franzholz/table/commit/1b60efe84d205c0ff55a92f404279f3c2ef773ab has a side effect: an input of a query that contains `REGEXP '^[[:blank:]]*(Blue)[[:blank:]]*$'` becomes `REGEXP '^[[:blank:]]*(Blue) [[:blank:]]*$'`, notice the space before `[[;blank:]]` that brakes the regular expression.

**Comment by franzholz** [comment] 2020-05-25 07:09
There is already a new entry for REGEXP. This needs special treatment anyways.

https://github.com/franzholz/table/issues/3

**Comment by webian** [comment] 2020-05-25 09:52
I didn't get what this has to do with #3.
